### ISSUE TITLE
Recent Rasterio breaks rio-mbtiles

### ISSUE THREAD

**Issue by sgillies** [mapbox/rio-mbtiles#13]
```
with rasterio.open('/vsimem/tileimg', 'w', **kwds) as tmp:
```

as used in mbtiles/__init__.py doesn't work with Rasterio 0.31. Reverting to 0.29 is a temporary work around.

**Comment by perrygeo** [comment]
Looks like support for `vsi` paths is back in Rasterio 1.0? It's not something we should count on though; we can do the reproject operation with a temporary dataset wrapper.
