### ISSUE TITLE
wrond dataset of mbtiles and png/jpg files

### ISSUE THREAD

**Issue by spatialhast** [mapbox/rio-mbtiles#14]
I install rio-mbtiles on Ubuntu 14.04.3 and try create mbtiles from my raster and raster in tests/data/ folder:  
rio mbtiles RGB.byte.tif -o raster.mbtiles -j 4 --format PNG --image-dump /home/box/rio-mbtiles/tests/data
mbtiles and image tiles successfully created but image tiles (png and jpg) don't opened in standart image files viewer. Also mbtiles file don't opened in QGIS (opened as tables (tiles and metadata)) or another mbtiles viewer. Example output data available on link https://www.dropbox.com/s/kfg2pywe9q21adx/rio-mbtiles_data.zip?dl=0
How I can get valid mbtiles?

**Comment by sgillies** [comment]
Got a fix for this coming in 1.3.0, but it will require a rasterio upgrade to >=1.0a1.
