### ISSUE TITLE
valueError: src_nodata must be provided because dst_nodata is not None

### ISSUE THREAD

**Issue by wandergis** [mapbox/rio-mbtiles#15]
When i run a sample,i got an error as it below.How can i set the nodata value with cli?
![image](https://cloud.githubusercontent.com/assets/5799374/14915163/35385392-0e43-11e6-9b31-8ad84e101f01.png)

**Comment by sgillies** [comment]
@wandergis I'm happy to add a nodata value option for version 1.3.0.
