### ISSUE TITLE
need way to force overwrite, rasterio 1.0 compat

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-mbtiles#17]
Recent Rasterio versions require explicit flags to overwrite existing files.

Two problems here:
1. Our test suite tries to overwrite the test fixtures. They should probably just be written to temp space, right?
2. We have no way to specify `--force-overwrite` at the CLI should we want this behavior. 

In `cli.py` we use `from rasterio.rio.helpers import resolve_inout` which takes a ` force_overwrite` keyword argument. We could pass `True` and keep the old behavior if needed.

**Comment by brendan-ward** [comment]
@perrygeo also see some of the commits in #16
