### ISSUE TITLE
travis fails to build Rasterio

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-mbtiles#19]
`rasterio/_base.c:287:22: fatal error: cpl_conv.h: No such file or directory` - looks like no python-dev. In fact, looks like this repo is set up to use old linux wheels.

@sgillies maybe this would be a good place to employ the manylinux wheels for 1.0a1?

**Comment by sgillies** [comment]
@perrygeo agreed, I'll look into that after lunch.
