### ISSUE TITLE
How to call mbtiles from python?

### ISSUE THREAD

**Issue by brunorpinho** [mapbox/rio-mbtiles#27]
I have a list of .tif filenames as strings and I want to create a bunch of mbtiles. I can't figure out how to do it from a python script.

**Comment by brunorpinho** [comment]
I tried:
```
from click.testing import CliRunner
CliRunner().invoke(mbtiles, ['./ASTER_GDEM.tif', './ASTER_GDEM.mbtiles'])
```
Output:
`<Result TypeError("'NoneType' object has no attribute '__getitem__'",)>`

**Comment by sgillies** [comment]
@brunorpinho I haven't considered using `CliRunner` outside the tests. This is a clever idea. It could work better if you follow the exact usage at https://github.com/mapbox/rio-mbtiles/blob/master/tests/test_cli.py#L35, which will ensure that the command objects are properly configured.
