### ISSUE TITLE
support for multifile tile conversion

### ISSUE THREAD

**Issue by jdmcbr** [mapbox/rio-mbtiles#32]
`rio mbtiles` currently does not complain if a user passes in multiple input files, but takes the first input file, converts to mbtiles, and ignores the rest. I took a very quick crack at support for multiple input files, expected it to fail where one tile included data from two (or more) input files, and confirmed that it failed. I have not spent any more time looking into how difficult it would be to support inserting data from multiple files. @sgillies Given the CLI takes multiple input files, I thought it might be something that you'd already given some thought to, so wanted to check in for your sense of feasibility and desirability of this before proceeding any farther on this myself.

The use case I ran into myself that motivated this was generating mbtiles for a very large raster, of which only about 5% were data pixels. Processing these in multiple files that were each basically 100% data was considerably faster, and for certain situations I had, I actually got acceptable results in splitting up the processing to be done with multiple files rather than one. It seems plausible that there's another way of going about this by differently handling areas of nodata within a large raster.

**Comment by sgillies** [comment]
@jdmcbr the support for multiple files isn't well thought out, to be honest. On the one hand, I'm hesitant to have rio-mbtiles take on the compositing of sources when they overlap. On the other hand, I'd love to see it write only the tiles that contain data and read the least amount of source data needed to make those tiles. If you've got ideas, I'm all ears (or eyes).

**Comment by jdmcbr** [comment]
@sgillies Thanks for filling me in, that makes sense. I don't have much knowledge of the inner workings of tiles, but checking for combining sources where they overlap in tiles didn't seem that desirable to me either. I'll investigate whether the other direction holds much promise.

**Comment by jdmcbr** [comment]
Closing this as #34 indirectly solves the issue that motivated me here.
