### ISSUE TITLE
Add 512x512 tile option

### ISSUE THREAD

**Issue by sgillies** [mapbox/rio-mbtiles#33]
512x512 tiles play better with the Mapbox platform and are a win for users that want to upload mbtiles and make Mapbox tilesets.

**Comment by jdmcbr** [comment]
I played with this a bit ago (on a branch off of the `skip-empty-tiles` branch), and discovered that at least for a subset of the images I'm working with, the 512x512 option resulted in some tiles that were too large for mapbox (above the 500kb limit). I'm not sure if I'm just unusual, but 256x256 tiles might be a better default.
