### ISSUE TITLE
Create non-CLI version of tile export

### ISSUE THREAD

**Issue by jdmcbr** [mapbox/rio-mbtiles#45]
I'd like to export datasets as tiles files within python calls, rather than using the CLI. Essentially thinking something that (using all default arguments) looked like:

```
import mbtiles
mbtiles.export(tiff_filename, tiles_filename)
```

Is this of any interest? Back when I did this for `rasterio.merge` (https://github.com/mapbox/rasterio/pull/460), keeping file i/o out of the core merge functionality was important. It doesn't seem like there's any useful version of the `mbtiles.export` I'm suggesting that wouldn't actually take a file in and generate a tiles file.

**Comment by sgillies** [comment]
@jdmcbr sorry I missed this. Sounds good to me if it is still useful to you.

**Comment by jdmcbr** [comment]
It doesn't look like this will have a ton of relevance to me in the not-too-distant future, so I probably won't get to it at this point. Thanks!
