### ISSUE TITLE
How to deal with large data sets and how to avoid auto projection transformation of Rio mbtiles?

### ISSUE THREAD

**Issue by ten2net** [mapbox/rio-mbtiles#69]
**I have two questions to help with:**

1. Do you have any good suggestions for converting large gtiff data sets (> 100g) to mbtiles?
2. Why does Rio mbtiles have to be converted to Mercator 3857 projection? Can we not use automatic projection conversion?

**Comment by sgillies** [comment]
@ten2net thanks for the questions! The discussion group at https://rasterio.groups.io/g/main is the principal support forum for rasterio and its plugins, but I haven't made that clear in this repo.

1. rio-mbtiles isn't designed for 100 GB datasets. To scale it up, I recommend dividing the GeoTIFF, send the parts to different servers, run rio-mbtiles on the parts, and then combine the mbtiles databases at the end.
2. The MBTiles format only supports the Web Mercator projection. See https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#content-1. If you want to work around that for some other coordinate reference system, all I can do is recommend https://gdal.org/programs/gdal2tiles.html.

**Comment by ten2net** [comment]
Thank you very much for your answer.
Is there any plan to launch a data processing pipeline (including split transform merge) based on rasterio processing large gtiff?
I use GDS_ Translate is used to implement segmentation, and Rio mbtiles is used to realize conversion. It is expected that Rio mbtiles with - append option can be used to merge. However, the merged mbtiles I got are not correct. There is a gap in the middle. Do you know which link I mentioned?
