### ISSUE TITLE
Feature request: add support for PNG8

### ISSUE THREAD

**Issue by Adrianod** [mapbox/rio-mbtiles#70]
Thank you for making rio-mbtiles, it's great.
I'm wondering if it would be possible to add support for PNG8, which produces drastically smaller file sizes for png tiles.

Thanks.

**Comment by sgillies** [comment]
@Adrianod you mean 8 bit PNG when the input file is an 8 bit raster? Making a conversion from RGB input rasters to PNG8 output is beyond the scope of rio-mbtiles.

**Comment by Adrianod** [comment]
Sorry, I was a bit unclear. I did some more research and what I'm after is adding the option of running the PNG tiles through a PNG compressor, for example [pngquant](https://github.com/kornelski/pngquant), which reduces the numbers of colors in a smart way, reducing file sizes by 60–80%. 
After I wrote this feature request I worked out a solution my own. I'm extracting the PNGs out of the mbtiles, optimizing the PNGs, and then repackaging to mbtiles again, like this:

```#create initial tiles
rio mbtiles -o tiles.mbtiles -f PNG --rgba --zoom-levels 13..14 input.tif

#extract to folder
mb-util tiles.mbtiles tmp

#optimize pngs
find . -name 'tmp/*.png' -print0 | xargs -0 -P8 -L1 pngquant --ext .png --force 256

rm tiles.mbtiles

#build mbtiles again
mb-util tmp tiles.mbtiles
```

This solution works really well for me, so I don't really need rio-mbtiles to do it for me. But still it might be useful to have the option built in? I'm leaving that decision up to you :)

**Comment by sgillies** [comment]
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize might be useful. I'll tentatively add this to the 1.6 milestone.

**Comment by sgillies** [comment]
Version 1.6a2 on PyPI now can take 8-bit files as input and make 8-bit PNG or WebP output. It doesn't quantize 24-bit imagery, which I've decided is out of scope for 1.6.
